spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ddia
    username: ddia
    password: ddia
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
